name: test main
on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      ref: ${{ github.sha }}

  # mirror_container_images:
  #   needs: [lint]
  #   uses: ./.github/workflows/sync-images.yaml
  #   secrets: inherit
  #   with:
  #     ref: ${{ github.sha }}

  # ensure_capi_images:
  #   needs: [lint]
  #   uses: ./.github/workflows/ensure-capi-images.yaml
  #   secrets: inherit
  #   with:
  #     ref: ${{ github.sha }}

  # publish_charts:
  #   needs: [lint]
  #   uses: ./.github/workflows/publish-charts.yaml
  #   secrets: inherit
  #   with:
  #     ref: ${{ github.sha }}

  # test:
  #   needs: [mirror_container_images, ensure_capi_images, publish_charts]
  #   uses: ./.github/workflows/test.yaml
  #   secrets: inherit
  #   with:
  #     # Pass the images as JSON
  #     images: ${{ toJSON(needs.ensure_capi_images.outputs) }}
  #     # Pass the chart version to test
  #     chart-version: ${{ needs.publish_charts.outputs.chart-version }}
  #     # We want to test the current sha
  #     ref: ${{ github.sha }}
  #     # Only run the sanity check on main
  #     tests-full: false
